Repository ortelius/ortelius.io, pull requests merged in 2024-10, with the labels that each got.

#202 Blog | Gleaming the FinOps Void
  content/en/blog/contributors/gleaming-the-finops-void.md
  package-lock.json
  static/images/brendan-walsh.jpg
  static/images/gleaming-the-finops-void.png
  yarn.lock
Labels: documentation

#204 Blog fixes and updates
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part03.md
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part07.md
  static/images/how-to-bake-an-ortelius-pi/part07/01-netdata-pods.png
Labels: documentation, hacktoberfest

#205 🛠 NEW: how to bake an ortelius pi part 7 updates
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part07.md
  static/images/how-to-bake-an-ortelius-pi/part07/05-netdata-connect-nodes.png
  static/images/how-to-bake-an-ortelius-pi/part07/06-netdata-existing-cluster.png
  static/images/how-to-bake-an-ortelius-pi/part07/07-netdata-nodes-123.png
  static/images/how-to-bake-an-ortelius-pi/part07/08-netdata-nodes-456.png
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#206 How to bake an Ortelius Pi | Fixes and updates to Jenkins and Netdata
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part05.md
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part07.md
  static/images/how-to-bake-an-ortelius-pi/part05/35-jenkins-discord-notification.png
  static/images/how-to-bake-an-ortelius-pi/part05/36-jenkins-plugin-discord-notifier.png
Labels: documentation, hacktoberfest

#207 message and integration
  content/en/_index.md
  static/images/2024HolidayParty.png
  static/images/2024HolidayParty.psd
  static/images/2024HolidayPartyBanner.png
  static/images/2024HolidayPartyBanner.psd
Labels: hacktoberfest-accepted, hacktoberfest

#208 How to bake an Ortelius Pi fixes, publication dates and updates
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part02.md
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part03.md
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part04.md
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part05.md
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part06.md
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part07.md
  static/images/how-to-bake-an-ortelius-pi/part05/10-jenkins-pvc.png
  static/images/how-to-bake-an-ortelius-pi/part05/24-jenkins-credentials-gh-pat.png
  static/images/how-to-bake-an-ortelius-pi/part05/37-jenkins-discord-channel-cog.png
  static/images/how-to-bake-an-ortelius-pi/part05/38-jenkins-discord-channel-webhook.png
  static/images/how-to-bake-an-ortelius-pi/part05/39-jenkins-credentials-gh-pat-secret-text.png
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#209 How to bake an Ortelius Pi 5 Jenkins marries Ortelius | missing images
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part05.md
  static/images/how-to-bake-an-ortelius-pi/part05/10-jenkins-pvc.png
  static/images/how-to-bake-an-ortelius-pi/part05/31-jenkins-multibranch-pipeline-build-now.png
  static/images/how-to-bake-an-ortelius-pi/part05/32-jenkins-multibranch-pipeline-build-job.png
  static/images/how-to-bake-an-ortelius-pi/part05/33-jenkins-multibranch-pipeline-build-pod.png
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#210 The Continuous Software Supply Chain Versioning Read USe case needs to be updated
  config.toml
  content/en/_index.md
  content/en/catalog/_index.md
  content/en/events/_index.md
Labels: hacktoberfest-accepted, hacktoberfest

#211 The Supply chain evidence use case should be changed to aggregate sboms
  content/en/versioning/index.md
Labels: hacktoberfest-accepted, hacktoberfest

#213 How to bake an Ortelius Pi Part 8 | OS Upgrades, Microk8s Upgrades and Adding Worker Nodes
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part01.md
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part03.md
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part04.md
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part05.md
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part06.md
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part07.md
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part08.md
  static/images/how-to-bake-an-ortelius-pi/part08/01-choose-ubuntu-server-24-04-1-lts-x64.png
  static/images/how-to-bake-an-ortelius-pi/part08/02-pi-nodes-k8s-stack.jpeg
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#214 fix page layout
  content/en/_index.md
  content/en/catalog/_index.md
  content/en/events/_index.md
  content/en/microservicemapping/index.md
  content/en/versioning/index.md
  static/images/2024HolidayParty.png
  static/images/2024HolidayParty.psd
  static/images/2024HolidayPartyBanner.png
  static/images/2024HolidayPartybanner-black.png
  static/images/2024HolidayPartybanner-black.psd
  static/images/Fullscreen-OpenSSF-HR-1.svg
  static/images/Vulnerabilites.svg
  static/images/applicationandcomponents.png
  static/images/devopsdetials-1.avif
  static/images/fullscreen-SBOM-Applicationlevel-sample.avif
  static/images/fullscreen-vulnerabilities.png
  static/images/ortelius-consolidate-concept.png
  static/images/sbom-application.png
Labels: hacktoberfest-accepted, hacktoberfest

#215 How to bake an Ortelius Pi | Cosmetics and fixes
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part01.md
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part02.md
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part03.md
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part05.md
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part06.md
  content/en/blog/contributors/how-to-bake-an-ortelius-pi-part08.md
  static/images/how-to-bake-an-ortelius-pi/part02/14-syno-file-share-nfs-config.png
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#216 Update content
  content/en/catalog/_index.md
  content/en/versioning/index.md
Labels: hacktoberfest-accepted, hacktoberfest

#218 Pr1
  content/en/blog/contributors/Ortelius IntegrationWithOSV.dev_blog.md
  content/en/blog/contributors/OrteliusIntegrationWithSPDXblog.md
  content/en/blog/contributors/Understanding SBOM and their Use.md
  static/images/CycloneDX JSON example.png
  static/images/DevSecOps Workflow.png
  static/images/SPDXJSON Sample.png
  static/images/Sample SBOM Working Report.png
  static/images/Vulnerabilities.png
  static/images/sample sbom gets updated during the build.png
Labels: hacktoberfest-accepted, hacktoberfest

#221 fix logo
  content/en/events/_index.md
Labels: hacktoberfest-accepted, hacktoberfest
